### PR TITLE
Sprockets 4 support with fix

### PR DESCRIPTION
**Pull request by merqlove**

### CODE REVIEW

**Comment by merqlove** [comment]
Travis fails with old JRuby deps. Maybe update it to 2.0 compatible?

**Comment by merqlove** [comment]
@pitr hello, can you look here, please?

**Comment by merqlove** [comment]
Seems it works well, site-maps especially.
Just made second try to integrate all with Sprockets 4.
We have a lot of assets in our angular app. (Something about 100+). 

And seems it works. With sitemaps it feels much much faster in development.
Sprockets 4 is awesome!

For those who also using AA, now they merged my similar patch.
https://github.com/activeadmin/activeadmin/pull/4528

**Comment by merqlove** [comment]
@pitr, Seems it's ok currently.
I have refactored source into multi-Tilt `Transformer` singleton.
Added cache_key to the transformer.
Upgraded JRuby in the Travis.
So now all checks for Sprockets version sits in the transformer.

**Comment by pitr** [comment]
LGTM thanks @merqlove

**Pull request merged**
