### PR TITLE
Fix for rails engines

### PR DESCRIPTION
**Pull request by danhawkins**
When using rails engines looking only in the assets at root fails

### CODE REVIEW

**Comment by novarac23** [comment]
+1 for this! @danhawkins any attempt at fixing failing tests ? I am even willing to pair on this just to make this PR pass  since I am getting pretty frustrated with having to use an old version of `sprockets`.

**Comment by novarac23** [comment]
Looks like there is a fix to support for `sprockets ~> 3.0` but its in a separate gem https://github.com/pitr/angular-rails-templates/pull/111 ! Hope this helps :)

**Comment by danhawkins** [comment]
@novarac23 I am not entirely sure why the tests are failing, they pass every time locally

**Comment by novarac23** [comment]
@pitr any ideas on why @danhawkins tests are not passing ?

**Comment by bradgreens** [comment]
Not necessarily my place to chime - but if I understand the CI report - it appears the tests fail when run against a Rails 3 Gemset. https://travis-ci.org/pitr/angular-rails-templates/jobs/100214942

**Comment by danhawkins** [comment]
I'll have another look this weekend

**Comment by pitr** [comment]
If you need this on Rails 4.2+ then please merge latest master into this branch.

If you need this on Rails 4.1 and earlier, then please reopen based on 0-x-stable branch.

Both master and 0-x-stable branches are now passing specs, so that should help with finding the reason for any test failures you might encouter

**Pull request closed without merging**
