### PR TITLE
support sprockets3 and rails 4.2

### PR DESCRIPTION
**Pull request by superchris**
So this works, but requires us to go back to .nghaml and .nghtml extensions. It also doesn't support slim or other formats yet. It won't hurt my feelings any if this gets rejected, but please let me know so I can't release as a different gem (angular-sprockets or something)

### CODE REVIEW

**Comment by hendricius** [comment]
Step into the right direction, thank you.

How would we go about adding `slim` support here?

**Comment by superchris** [comment]
I'm assuming the same approach would work that I took with haml, you'd have
to support an ngslim extension and then invoke Slim through its API.

**Comment by princemaple** [comment]
@pitr

**Comment by jeremyk** [comment]
BTW, I added slim support here: https://github.com/Eventshare/angular-rails-templates/commit/65eaae1f8095af315376d17efd1477a5111ba3dc

**Comment by hendricius** [comment]
:+1: jeremyk. looks great. 

So the only drawback is that we have to name the files `.nghtml.`. I don't find that too bad. It's also more explicit. People will know by looking what the files is actually about.

**Comment by princemaple** [comment]
@hendricius @superchris will this be released soon?

**Comment by thekendalmiller** [comment]
Using a template specific extension fixes would also fix html preprocessing. https://github.com/pitr/angular-rails-templates/issues/112

**Comment by superchris** [comment]
Hey, is this going to be merged and released? I'm going to go ahead and release this as new gem if not.

**Comment by tboerger** [comment]
@superchris when do you release your gem version?

**Comment by superchris** [comment]
I just released my fork as angular-rails4-templates.

**Comment by pitr** [comment]
Thanks @superchris ! I got this branch to work with old extensions like `.html` and `.html.haml` and such. Added you as a collaborator

**Pull request closed without merging**
